## Numpy Basics

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([2, 4, 6, 8])
print (arr_1d)

[2 4 6 8]


In [3]:
arr_2d = np.array ([[1,2,3], [2, 3, 5]])
print (arr_2d)

[[1 2 3]
 [2 3 5]]


In [4]:
list = [1, 2, 3]
print(list * 2)

# Element-Wise Multiplication

print (arr_2d * 4)

[1, 2, 3, 1, 2, 3]
[[ 4  8 12]
 [ 8 12 20]]


In [5]:
# can use np.arange(start, stop, step) to automatically create arrays
# numpy take less ammount of time than lists

import time
start = time.time()
lst = [i * 2 for i in range(1000000)]
print("time ->", time.time() - start)

start = time.time()
arr = np.arange(2000000) * 2
print ("time ->", time.time() - start)

time -> 0.08171391487121582
time -> 0.008481025695800781


In [6]:
zeros = np.zeros((5,2))
print(zeros)

ones = np.ones((1,7))
print(ones)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]]


In [7]:
# can make an array of any constant of a given dimension

const = np.full((3, 2, 3), 9)
print(const)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


In [8]:
# to get random values in btw 0 and 1

rand = np.random.random((3, 4))
print(rand)

[[0.51780416 0.26314381 0.87424986 0.12334972]
 [0.22510355 0.78724642 0.66474787 0.24255613]
 [0.83613489 0.09419468 0.88507985 0.54184368]]


In [9]:
# Gives you the shape in tensor
print(np.shape(rand))
print(rand.shape)

(3, 4)
(3, 4)


In [10]:
# Gives you the dimension of tensor
print (rand.ndim)

2


In [11]:
# Gives you the total number of elements 
print(rand.size)

12


In [12]:
# Gives you the data type
print(rand.dtype)

float64


In [13]:
print(rand.reshape(4,3))

[[0.51780416 0.26314381 0.87424986]
 [0.12334972 0.22510355 0.78724642]
 [0.66474787 0.24255613 0.83613489]
 [0.09419468 0.88507985 0.54184368]]


In [14]:
print(rand.flatten())

[0.51780416 0.26314381 0.87424986 0.12334972 0.22510355 0.78724642
 0.66474787 0.24255613 0.83613489 0.09419468 0.88507985 0.54184368]


In [15]:
# ravel returns view instead of copy
reshape = rand.reshape((12, 1))
print(reshape)
print(reshape.ravel())
print(reshape)
print(reshape.flatten())

[[0.51780416]
 [0.26314381]
 [0.87424986]
 [0.12334972]
 [0.22510355]
 [0.78724642]
 [0.66474787]
 [0.24255613]
 [0.83613489]
 [0.09419468]
 [0.88507985]
 [0.54184368]]
[0.51780416 0.26314381 0.87424986 0.12334972 0.22510355 0.78724642
 0.66474787 0.24255613 0.83613489 0.09419468 0.88507985 0.54184368]
[[0.51780416]
 [0.26314381]
 [0.87424986]
 [0.12334972]
 [0.22510355]
 [0.78724642]
 [0.66474787]
 [0.24255613]
 [0.83613489]
 [0.09419468]
 [0.88507985]
 [0.54184368]]
[0.51780416 0.26314381 0.87424986 0.12334972 0.22510355 0.78724642
 0.66474787 0.24255613 0.83613489 0.09419468 0.88507985 0.54184368]


In [16]:
transpose = reshape.T
print(transpose)

[[0.51780416 0.26314381 0.87424986 0.12334972 0.22510355 0.78724642
  0.66474787 0.24255613 0.83613489 0.09419468 0.88507985 0.54184368]]


### Numpy Operations

In [17]:
#slicing
arr = np.arange(5, 50, 5)
print(arr[4:7])

[25 30 35]


In [18]:
rand = np.random.random((3,3))
print(rand)
print("Specific Element", rand[2,2])
print("Entire row", rand[0])
print("Entire column", rand[:, 2])

[[0.75434737 0.94583025 0.82877406]
 [0.8390082  0.23733734 0.69667146]
 [0.67594302 0.07359148 0.0905582 ]]
Specific Element 0.09055819718025038
Entire row [0.75434737 0.94583025 0.82877406]
Entire column [0.82877406 0.69667146 0.0905582 ]


In [19]:
unsorted = np.array([2,7,1,5,0])
print(np.sort(unsorted))

unsort = np.array([[4, 6],
                   [7, 2],
                   [1, 4]])
print("Whole sort", np.sort(unsort, axis = 0))
print("Sort in each row", np.sort(unsort, axis = 1))

[0 1 2 5 7]
Whole sort [[1 2]
 [4 4]
 [7 6]]
Sort in each row [[4 6]
 [2 7]
 [1 4]]


In [20]:
# Expressions can be used instead of indexes in numpy
# called as filtering and expression can be called as mask

numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])
even = numbers[numbers % 2 == 0]
print(even)

mask = numbers < 7
print(numbers[mask])

[2 4 6 8]
[1 2 3 4 5 6]


In [21]:
# fancy indexing

indices = [3, 4, 1]
print(numbers[indices])

[4 5 2]


In [22]:
# where in numpy

where_result = np.where(numbers>5)
print(where_result)
print(numbers[where_result])

(array([5, 6, 7]),)
[6 7 8]


In [23]:
arr1 = np.array([2, 4, 5])
arr2 = np.array([2, 7, 9])
print(arr1 - arr2)

[ 0 -3 -4]


In [24]:
print(np.concatenate((arr1, arr2)))

[2 4 5 2 7 9]


In [25]:
# Combining arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([5, 6])
arr3 = np.array([[7], [8]])

# vertical stacking
print(np.vstack((arr1, arr2)))

# horizontal stacking
print(np.hstack((arr1, arr3)))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [28]:
arr = np.array([1, 2, 3, 4, 5])
deleted1 = np.delete(arr, 0)
deleted2 = np.delete(arr, [0, 4, 2])              #index of start, end, step
print(deleted1, "\n", deleted2)

[2 3 4 5] 
 [2 4]


In [1]:
import os
os.getcwd()

'C:\\Users\\maste'